## numpy.array 中的运算

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
2*L # apped

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []
for e in L:
    A.append(2*e)

In [5]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
n = 100000
L = [i for i in range(n)]

In [7]:
%%time
A = []
for e in L:
    A.append(2*e)

CPU times: user 12.4 ms, sys: 2.05 ms, total: 14.5 ms
Wall time: 13.6 ms


In [10]:
%%time
A=[2*e for e in L]

CPU times: user 4.99 ms, sys: 759 µs, total: 5.75 ms
Wall time: 5.41 ms


In [11]:
import numpy as np

In [12]:
L = np.array(2*e for e in L)

In [15]:
A = np.array(2*e for e in L)

TypeError: iteration over a 0-d array

In [16]:
X = np.arange(1,16).reshape((3,5))

In [17]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
 X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [19]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [21]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [22]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [23]:
X ** 2


array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [24]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [25]:
1/X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [26]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [28]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [29]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [30]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [31]:
np.exp2(X)

array([[2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01],
       [6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03],
       [2.0480e+03, 4.0960e+03, 8.1920e+03, 1.6384e+04, 3.2768e+04]])

In [32]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

## 矩阵运算

In [33]:
A = np.arange(4).reshape(2,2)

In [34]:
A

array([[0, 1],
       [2, 3]])

In [35]:
B = np.full((2,2),10)

In [36]:
B

array([[10, 10],
       [10, 10]])

In [37]:
A+B

array([[10, 11],
       [12, 13]])

In [38]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [39]:
A*B

array([[ 0, 10],
       [20, 30]])

In [40]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [41]:
C = np.full((3,3),666)

In [42]:
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [43]:
A+C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [44]:
A+C.reshape(2,2)

ValueError: cannot reshape array of size 9 into shape (2,2)

## 向量和矩阵的运算

In [45]:
v = np.array([1,2])
v

array([1, 2])

In [46]:
v+A

array([[1, 3],
       [3, 5]])

In [47]:
A

array([[0, 1],
       [2, 3]])

In [48]:
A.broadcast(v)

AttributeError: 'numpy.ndarray' object has no attribute 'broadcast'

In [49]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [50]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [51]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [52]:
v * A

array([[0, 2],
       [2, 6]])

In [53]:
v.dot(A)


array([4, 7])

## 矩阵的逆


In [54]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [55]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-2.46666667e-01, -6.66666667e-02,  1.13333333e-01],
       [-1.33333333e-01, -3.33333333e-02,  6.66666667e-02],
       [-2.00000000e-02, -2.51534904e-17,  2.00000000e-02],
       [ 9.33333333e-02,  3.33333333e-02, -2.66666667e-02],
       [ 2.06666667e-01,  6.66666667e-02, -7.33333333e-02]])