In [1]:
im

NameError: name 'im' is not defined

In [2]:
import numpy

In [3]:
numpy.__version__

'1.16.2'

In [5]:
L = [i for i in range[10]]

TypeError: 'type' object is not subscriptable

In [6]:
L

NameError: name 'L' is not defined

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Python List特点

In [8]:
L[5]

5

In [9]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [10]:
L[5] = "Machine Lenrning"
L

[0, 1, 2, 3, 4, 'Machine Lenrning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，带来效率问题。

In [11]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

5

In [15]:
arr[5] = 100

In [16]:
arr[5]

100

In [17]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [18]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [19]:
arr[5] = 5.0

TypeError: integer argument expected, got float

array的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

In [20]:
import numpy as np

In [21]:
np.__version__


'1.16.2'

In [24]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
nparr[5] =100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [26]:
nparr.dtype

dtype('int64')

In [27]:
nparr[5] = 5.0

In [28]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr2 = np.array([1,2,3.12])
nparr2

array([1.  , 2.  , 3.12])

In [30]:
nparr2.dtype

dtype('float64')