In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [4]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [5]:
x = np.arange(10)

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
X = np.arange(15).reshape((3,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## numpy.array的基本属性

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.shape
X.shape

(3, 5)

In [11]:
x.shape

(10,)

In [12]:
x.size

10

In [13]:
X.size

15

numpy.array 的数据访问

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [16]:
x[-1]

9

In [17]:
x[-2]

8

In [18]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
X[0][0]

0

In [20]:
X[0][1]

1

In [21]:
X[0,0]

0

In [22]:
X[0,1]

1

In [23]:
x[0:5] #左开右闭

array([0, 1, 2, 3, 4])

In [24]:
x[::2]

array([0, 2, 4, 6, 8])

In [25]:
x[1::2]

array([1, 3, 5, 7, 9])

In [26]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [32]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
X[:,0]

array([ 0,  5, 10])

In [34]:
X[0,:]

array([0, 1, 2, 3, 4])

Subarray of numpy.array

In [36]:
subX = X[:2,:3]

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
X[0,0] = 100

In [40]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [42]:
subX = X[:2,:3].copy()

In [43]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

Reshape

In [44]:
x.shape

(10,)

In [45]:
X.shape

(3, 5)

In [46]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
A = x.reshape(2,5)

In [49]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
B = x.reshape(1,10)

In [51]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
B.ndim

2

In [54]:
B.shape

(1, 10)

In [55]:
x.reshape(3,-1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)