In [1]:
import numpy as np

In [2]:
X = np.random.normal(0,1,100000)

In [3]:
X

array([ 0.69020719, -0.59322229, -0.0100057 , ...,  0.63876418,
       -0.09179294, -0.24725262])

In [4]:
np.argmax(X)

27430

In [5]:
np.argmin(X)

85175

In [6]:
X[85175]

-4.266576454260244

In [7]:
np.min(X)

-4.266576454260244

## 排序和使用索引

In [8]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
np.random.shuffle(x)

In [10]:
x

array([ 5, 11, 12,  4,  1, 13, 10,  8,  0,  6,  7,  2, 14,  9, 15,  3])

In [11]:
np.sort(x)
x

array([ 5, 11, 12,  4,  1, 13, 10,  8,  0,  6,  7,  2, 14,  9, 15,  3])

In [12]:
x

array([ 5, 11, 12,  4,  1, 13, 10,  8,  0,  6,  7,  2, 14,  9, 15,  3])

In [13]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x.sort()

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
X = np.random.randint(10,size=(4,4))
X

array([[1, 7, 3, 9],
       [6, 9, 5, 6],
       [8, 1, 1, 5],
       [5, 7, 2, 9]])

In [17]:
np.sort(X,axis=0)

array([[1, 1, 1, 5],
       [5, 7, 2, 6],
       [6, 7, 3, 9],
       [8, 9, 5, 9]])

In [18]:
np.sort(X,axis=1)

array([[1, 3, 7, 9],
       [5, 6, 6, 9],
       [1, 1, 5, 8],
       [2, 5, 7, 9]])

## 使用索引

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
np.random.shuffle(x)

In [21]:
x

array([13,  9,  5, 11,  0,  4, 12,  3, 15,  1, 10,  6, 14,  8,  7,  2])

In [23]:
np.argsort(x)

array([ 4,  9, 15,  7,  5,  2, 11, 14, 13,  1, 10,  3,  6,  0, 12,  8])

In [24]:
np.partition(x, 3)

array([ 0,  2,  1,  3, 11,  4, 12,  9, 15,  5, 10,  6, 14,  8,  7, 13])

In [25]:
np.argpartition(x, 3)

array([ 4, 15,  9,  7,  3,  5,  6,  1,  8,  2, 10, 11, 12, 13, 14,  0])

In [26]:
np.argsort(X, axis=1)

array([[0, 2, 1, 3],
       [2, 0, 3, 1],
       [1, 2, 3, 0],
       [2, 0, 1, 3]])

In [27]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 1, 3],
       [2, 0, 3, 1],
       [1, 2, 3, 0],
       [2, 0, 1, 3]])